### ISSUE TITLE
Modify XorT and OptionT variance

### ISSUE THREAD

**Issue by frosforever** [typelevel/cats#556] opened 2015-10-02 23:06 UTC
`Xor` is currently covariant while `XorT` is invariant.

Assuming one has the following:

``` scala
sealed trait Error
case class ErrorA(message: String) extends Error
case object ErrorB extends Error
```

with `Xor` one can have something that looks like:

``` scala
val t: Xor[Error, Int] = for {
  i <- Xor.left[ErrorB.type, Int](ErrorB)
  r <- Xor.left[ErrorA, Int](ErrorA("foo"))
} yield r
```

However the same using `XorT` will not compile:

``` scala
val noCompile: XorT[List, Error, Int] = for {
  i <- XorT(List(Xor.left[ErrorB.type, Int](ErrorB)))
  r <- XorT(List(Xor.left[ErrorA, Int](ErrorA("foo"))))
} yield r
```

and one is instead forced to use

``` scala
val tf: XorT[List, Error, Int] = for {
  i <- XorT(List(Xor.left[Error, Int](ErrorB)))
  r <- XorT(List(Xor.left[Error, Int](ErrorA("foo"))))
} yield r
```

Because `Xor` is covariant, the non-monad-transformer version of `noCompile` compiles just fine:

``` scala
val compiles: List[Xor[Error, Int]] = List(Xor.left[ErrorB.type , Int](ErrorB)).flatMap { e1 =>
  List(Xor.left[ErrorA, Int](ErrorA("foo"))).map { e2 =>
    e1.flatMap { i =>
      e2.map { r =>
        r
      }
    }
  }
}
val compilesXorT = XorT[List, Error, Int](compiles)
```

I do not know which one is more correct but it is confusing for `Xor` and `XorT` not to behave in the same way. If this is indeed the expected and correct behavior perhaps we can add some documentation to prevent confusion.

Note: the same can be said for `OptionT` though I came across this using `Xor` and so these are the examples I've got.

**Comment by ceedubs** [comment] 2015-10-03 13:51
Thanks for raising this issue and providing a detailed explanation @frosforever! I agree that we should do something about this, even if that "something" is just better documentation. Here is a bit of a brain dump on my thoughts on the matter.

In Scala, variance has both positives and negatives (perhaps that's how they decided on variance notation! :P). These pros/cons have been discussed numerous times in various venues, so I won't go into them now, but in my opinion at the end of the day you kind of have to settle on "to each their own".

I think this "to each their own" means that you can't force variance on a type constructor. A concrete example is [`scalaz.Free` in the 7.0 series](https://github.com/scalaz/scalaz/blob/series/7.0.x/core/src/main/scala/scalaz/Free.scala#L75). It forces the `S` type constructor to be covariant. At the time I often wanted to wrap a [`Coyoneda`](https://github.com/scalaz/scalaz/blob/series/7.0.x/core/src/main/scala/scalaz/Yoneda.scala#L41) in `Free`. The most recent versions of Cats and Scalaz have the `Coyoneda` essentially built into the `Free`, so this particular use might not be as desired now, but the general principle applies. The problem is that `Coyoneda` is invariant, so you simply couldn't do this (without a mess of `@uncheckedVariance`)! By making type constructor parameters invariant, you may end up forcing people to be more explicit about types, but I think that it beats the alternative, where you can prevent them from being able to use your type at all.

Does that make sense? Is there a best-of-both-worlds approach that I'm overlooking?

**Comment by zainab-ali** [comment] 2016-07-25 12:33
I prefer invariance for the reasons above, but still need a workaround to widen errors.
What do you think about adding a `leftWiden` on `XorT`?  I'd be happy to make a PR for it.

**Comment by ceedubs** [comment] 2018-03-24 22:40
I'm going to go ahead and close this out for a few reasons:

- It's quiet for a long time.
- As mentioned above, there are issues with forcing variance into type constructors that are used within `EitherT`.
- Now that we have `widen` and `leftWiden`, this is easier to work around.

**Closed by ceedubs** 2018-03-24 22:40 UTC

**Comment by i-am-the-slime** [comment] 2024-08-06 09:17
Why not have both in the library? `OptionTCo`, `EitherTCo`, etc.
Writing `leftWiden` everywhere I want to use `EitherT` is extremely ugly and avoidable, no?
