### ISSUE TITLE
Validate should validate Scaladocs too

### ISSUE THREAD

**Issue by non** [typelevel/cats#516] opened 2015-09-02 23:32 UTC
Right now it's possible to have Scaladoc errors which aren't caught by `validate`.

We should have it run `compile:doc` (or similar) for each project in addition to the other work it is doing.

**Comment by ceedubs** [comment] 2015-09-03 23:15
@non I'm unable to reproduce this. Do you have an example of a change that should cause it to fail but doesn't? It includes a `makeSite` call, which should compile the ScalaDocs.

**Comment by non** [comment] 2015-09-03 23:51
In the `BimonadLaws` scaladoc, change the "`Bimonad`" to a "[[Bimonad]]" and run `laws/compile:doc`.

**Comment by ceedubs** [comment] 2015-09-04 00:12
Ah, I suspect this and #510 have the same root cause.

**Comment by ceedubs** [comment] 2015-09-04 00:15
I think I see the issue. PR incoming.

**Comment by ceedubs** [comment] 2015-09-04 01:02
Hmm. I thought it was as easy as adding the laws project to https://github.com/non/cats/blob/672e0105f2d0136c3185ff79300a002384a2ec8b/build.sbt#L58 but I get some bizarre errors if I try to do that. I'm not sure what is going on.

**Comment by non** [comment] 2015-09-04 01:12
Ohhhh, now I'm almost remembering something. I think maybe we hit these errors a long time ago and disabled the laws project because we didn't understand them.

I also wonder if any of this is related to #510.

**Comment by mikejcurry** [comment] 2015-11-29 12:50
Investigated this for a little. After making the change outlined @ceedubs the doc build starts to fail. Some observations:
* For the most part the issues are confined to a couple of areas 
 * References to `Foldable` typeclass syntax 
 * References to `Apply` typeclass syntax 
* Example:
 * `TraverseLaws` references an implicit `Traversable[F]`
 * `TraverseLaws` also imports the `foldable` syntax 
 * At line 59, `TraverseLaws` tries to use this syntax `val rhs: B = fa.foldMap(f)`, but this fails compilation
 * Changing the code here to not use the syntax results in correct compilation, i.e. `val rhs: B = F.foldMap(fa)(f)` compiles successfully during doc generation 

Interestingly,
* The `Traverse` syntax used in the `TraverseLaws` is fine and compiles, so not all syntax is affected, and the `Traverse` syntax does not seem to use simulacrum for syntax, even though the typeclass uses simulacrum.
* References to the `Foldable` syntax in the `FoldableLaws` class is also failing, indicating that it is not specific to the usage in `Traverse`.
* A similar problem occurs with the `Apply` syntax in all areas that `Apply` syntax is used in the laws.

There is something peculiar about the specific syntax for these two type classes that when compiled in this specific context, the compilation is failing.

There may be other things at play here, and the path may end up being a dead end, but wanted to record this anyway in case it triggers any thoughts for anyone else.

**Comment by ceedubs** [comment] 2018-09-30 23:06
I think that this is due to #510, so I'm going to close it out as a duplicate of that.

**Closed by ceedubs** 2018-09-30 23:06 UTC
