### ISSUE TITLE
Add `MonadError` instance to `StateT`

### ISSUE THREAD

**Issue by jserranohidalgo** [typelevel/cats#1397] opened 2016-09-30 14:39 UTC
@non Proposal for ScalaCenter hackathon at Lambda World
If `MonadError[?[_],E]` is available for `F[_]`, then we can give a `MonadError[?[_],E]` instance for `StateT[F,S,?]`, for any F, S, E.

**Comment by adelbertc** [comment] 2016-09-30 15:23
Duplicate of https://github.com/typelevel/cats/issues/1378

**Comment by non** [comment] 2016-09-30 15:29
Makes sense to me. 👍 

@adelbertc I wouldn't call this a duplicate -- I think it's unlikely we'll get all the MTL instances in one PR. Maybe we could make sub-issues for particular instances (or groups of instances)?

**Comment by adelbertc** [comment] 2016-09-30 15:56
@non OK fair :-)

One thing I want to note is since this is related to `MonadError`/MTL, be cognizant of the issue still up in the air here: https://github.com/typelevel/cats/pull/1379#issuecomment-247878936

**Comment by non** [comment] 2016-09-30 16:22
Right! My sense is that if we get something soon we could merge it (and I could update it) -- or if we get a change first, then we might need to update a future PR.

**Comment by jvican** [comment] 2016-09-30 16:46
Hey @adelbertc and @non, would you mind labelling this as hackathon? :smile:

**Comment by adelbertc** [comment] 2016-10-01 00:51
@non On a related note have you thought about what the way forward should be? Your comment seems to imply an OK to move to the Scato encoding if someone did the work, or still unsure?

Alternatively, @paulp also suggested a better, language-level solution: https://twitter.com/extempore2/status/781996943207567360

**Comment by non** [comment] 2016-10-01 01:08
@adelbertc So -- I'm a few hours away from giving a talk at Lambda World, so I'm a bit distracted.

I'm largely OK with type classes containing other type classes (rather than extending them) but given the potential loss of coherence I think I prefer a model where you can might still just combine the `Monad` with something like `MonadCombine`, a la:

```scala
def something[F[_]: Monad: MonadCombine, A](fa: F[A]) = ...
```

I realize that looks somewhat bad, but I think it dodges the worst issues of composition (accessing the inner monad is really inconvenient and ugly). It might seem like we lose coherence here, but we've already lost it, given that users could always write this:

```scala
def foo[F[_]: Monad, A](fa: F[A]) = ...
def bar[F[_]: MonadCombine, A](fa: F[A]) = ...
```

Any code that calls `foo` and `bar` with the same `F` is already risking incoherence.

I think if we go with a compositional encoding, we need extra laws to check that the "default" implicit space provides coherent instances. We also need to try to combine up with relatively clear principles why someone should (or should not) use this encoding.

I'm pretty OK with using a different MTL encoding, but especially with something like `Traverse` getting affected I'm a bit nervous.

**Comment by adelbertc** [comment] 2016-10-01 01:32
Oh that's right, ignore me, let's talk more afterwards :-)

On Sep 30, 2016 18:08, "Erik Osheim" <notifications@github.com> wrote:

@adelbertc <https://github.com/adelbertc> So -- I'm a few hours away from
giving a talk at Lambda World, so I'm a bit distracted.

I'm largely OK with type classes containing other type classes (rather than
extending them) but given the potential loss of coherence I think I prefer
a model where you can might still just combine the Monad with something
like MonadCombine, a la:

def something[F[_]: Monad: MonadCombine, A](fa: F[A]) = ...

I realize that looks somewhat bad, but I think it dodges the worst issues
of composition (accessing the inner monad is really inconvenient and ugly).
It might seem like we lose coherence here, but we've already lost it, given
that users could always write this:

def foo[F[_]: Monad, A](fa: F[A]) = ...def bar[F[_]: MonadCombine,
A](fa: F[A]) = ...

Any code that calls foo and bar with the same F is already risking
incoherence.

I think if we go with a compositional encoding, we need extra laws to check
that the "default" implicit space provides coherent instances. We also need
to try to combine up with relatively clear principles why someone should
(or should not) use this encoding.

I'm pretty OK with using a different MTL encoding, but especially with
something like Traverse getting affected I'm a bit nervous.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/typelevel/cats/issues/1397#issuecomment-250883309>, or mute
the thread

**Closed** 2016-10-25 19:14 UTC
Labels: Hackathon
