### ISSUE TITLE
Tuple2 instances not imported with cats.implicits._

### ISSUE THREAD

**Issue by brinklec** [typelevel/cats#2585] opened 2018-10-28 19:04 UTC
As of 1.4, `Tuple2` instances covered by the specific imports `cats.instances.tuple.catsStdInstancesForTuple2` and `cats.syntax.functor.toFunctorOps` are apparently not covered by `cats.implicits._`.  It is possible to have both the general and the specific imports in the same location, which I believe would not be true if there were any overlap.  From comments by knowledgeable people on gitter, I assume it is intended that `cats.implicits._` should include these as well.

**Comment by ceedubs** [comment] 2018-10-29 02:46
@brinklec could you please share an example of what is failing for you? Things seem to be fine as far as I can tell:

```scala
scala> import cats.implicits._
import cats.implicits._

scala> ("foo", 3).map(_ + 1)
res0: (String, Int) = (foo,4)

scala> cats.Functor[(String, ?)]
res1: cats.Functor[[β$0$](String, β$0$)] = cats.instances.Tuple2Instances$$anon$4@2667212c
```

It's possible that they don't cause conflicts because of the details of implicit prioritization; I'm not sure. I'm not too worried about it as long as it doesn't cause anything to fail for anyone.

**Comment by brinklec** [comment] 2018-10-29 19:34
Looks like above comment was not saved when I thought it was.

I reported this because I was getting errors.  The subject code still has a few other issues, though, and the context is complex.  I just made an error reappear by commenting out the specific imports:
```
[error]  value map is not a member of (Set[recset.instances.Wire.PhysIntPin], scala.collection.immutable.Set[recset.instances.Wire.WireRsRec])
[error]           if ((x.map(_.map(y => visited(p1, y._1)))) && (x.map(_.map(y => visited(p2, y._1))))) {
[error]                        ^
```
If you need an actual gist, I'd like to clean up the other issues first.  Hope to complete that today.

**Comment by brinklec** [comment] 2018-10-30 17:02
Hmm, almost done working through the other issues, but just retested with the specific imports removed, and now seem to have lost reproducibility of the issue reported here.  At any rate, if this comes up again, I can always reinstate the more specific imports again.

Many thanks for the support.

**Comment by LukaJCB** [comment] 2018-11-03 09:36
Can this be closed out now @brinklec? :)

**Comment by brinklec** [comment] 2018-11-04 19:54
Please feel free to use your best judgment.  I wish I has better insight into whether or not this no longer reproducible error was somehow merely a stateful consequence of another error now corrected, or a due to a possibly still existing corner case.  This makes me think I should not really trust a compiler error to be telling me the truth unless I can reproduce it in isolation from all others, but that is certainly not a cats issue.  Thanks again for the responsive support.

**Comment by ceedubs** [comment] 2018-11-06 14:35
Thanks for the report @brinklec. I'm going to go ahead and close it out, and you can feel free to reopen it if you can reproduce the issue.

**Closed by ceedubs** 2018-11-06 14:35 UTC
