### ISSUE TITLE
No instance of Invariant for Numeric

### ISSUE THREAD

**Issue by aherrmann13** [typelevel/cats#3594] opened 2020-09-04 02:38 UTC
I can't find an instance of `Invariant` typeclass for `Numeric`.  Is there a reason this does not exist?  If not I can go ahead and implement it

**Comment by tmccarthy** [comment] 2020-09-22 10:56
Related are #3220 and #3222.

**Comment by larsrh** [comment] 2021-01-30 12:08
Closed as duplicate of #3220.

**Closed by larsrh** 2021-01-30 12:08 UTC
