### ISSUE TITLE
Add listen to IndexedReaderWriterStateT

### ISSUE THREAD

**Issue by djspiewak** [typelevel/cats#3270] opened 2020-01-27 04:11 UTC
Implementation:

```scala
      def listen[A](fa: IRWST[F, E, L, SA, SB, A]) =
        IRWST applyF {
          fa.runF map { f => (e: E, s: SA) =>
            f(e, s) map {
              case (l, s, a) => (l, s, (a, l))
            }
          }
        }
```

**Comment by LukaJCB** [comment] 2020-01-27 06:02
I think this is a duplicate of #2304

**Closed by LukaJCB** 2020-01-27 06:02 UTC
Labels: good first issue
