### ISSUE TITLE
Semigroup |+| is 4 times slower than scalaz Semigroup |+|

### ISSUE THREAD

**Issue by rayqiu** [typelevel/cats#1291] opened 2016-08-16 03:56 UTC
Semigroup |+| is 4 times slower than scalaz Semigroup |+|, when combining two large Maps that have nested Maps inside.  

Map type: Map[Seq[Char], Map[Char, Int]]

**Comment by adelbertc** [comment] 2016-08-16 05:15
Perhaps related to https://github.com/typelevel/cats/issues/1290

**Comment by ceedubs** [comment] 2016-08-18 12:38
Thanks for reporting this, @rayqiu. I think this is a duplicate of #1290, so I'm going to close it out. @rayqiu please feel free to reopen it if you have an example of another data type that is also slow with `|+|`.

**Closed by ceedubs** 2016-08-18 12:38 UTC
