### ISSUE TITLE
Add scalafmt formatting

### ISSUE THREAD

**Issue by YuvalItzchakov** [typelevel/cats#2484] opened 2018-09-10 14:44 UTC
I know this has a huge potential for bikeshedding, but I think it's worth it to keep the styling of the project in tact, especially for new comers (such as myself) who accidentally format using IDEA where each dev has his own custom setting.

I would be happy to take this on myself if this has consensus.

**Comment by kailuowang** [comment] 2018-09-10 15:03
I am 👍 ,  the time-consuming part is to keep the new rules as consistent as the current styling as possible to avoid unnecessary reformating.

**Comment by djspiewak** [comment] 2018-09-10 15:50
I love scalafmt in principle, and once the bikeshedding is done, the effect is usually very positive. *However* it's also very slow. This isn't really anyone's fault – the algorithm as designed is currently just slow, and there's an experimental replacement which is much faster – but it does mean that it can be impractical on certain codebases, even with plugins like neo-scalafmt.

This is what held us back from using scalafmt on quasar, for example.

Anyway, something to think about.

**Comment by YuvalItzchakov** [comment] 2018-09-10 16:02
Perhaps conducting a small POC and comparing before and after? Or has that been done already?

**Comment by LukaJCB** [comment] 2018-09-10 19:44
We don't have to run it on compile, right?

**Comment by YuvalItzchakov** [comment] 2018-09-10 20:03
@LukaJCB If we want to enforce the style, it has to be on compile since not everyone uses the scalafmt plugin for IDEA.

**Comment by rossabaker** [comment] 2018-09-10 20:26
http4s does not run it on compile, but tests it on CI (`test:scalafmt::test`).  This keeps the formatting consistent.  It also means a lot of PRs initially on that step, because few actually run the full `ci` step before opening a PR.  I tried enabling it at compile time, and found it added 30 seconds to the most trivial incremental builds.  On balance, I don't regret it, but it's not perfect.

> keep the new rules as consistent as the current styling as possible to avoid unnecessary reformating.

This sounds good, but I suspect the current styling is inconsistent enough to make this a difficult target.

**Comment by YuvalItzchakov** [comment] 2018-09-10 20:31
@rossabaker If the formatting happens only during CI, which steps formats and commits the correct style? Would we only let the CI fail the commit and have people manually fix it?

**Comment by rossabaker** [comment] 2018-09-10 21:26
http4s fails the build and makes people fix it.  This is irritating.

An alternative model we've discussed, but not implemented, is to have Travis CI push a commit to the PR that fixes the formatting.  We have some misgivings about CI directly modifying PRs, although we already let it publish the jars and the docs and the tags.

**Comment by djspiewak** [comment] 2018-09-10 21:29
@rossabaker There are some very rare cases where scalafmt can break things. Also some slightly less rare (but still rare) cases where it can get itself into loops (e.g. state **A** gets reformatted to state **B**, which gets reformatted to state **A**). It's hard to detect and resolve these things without human intervention.

**Comment by mpilquist** [comment] 2018-09-10 21:33
FWIW, I use scalafmt on compile on lots and lots of projects, both open & closed source, and I've never had problems with speed or generating bad code or loops. If such things did occur, I'd add a no-format comment to disable the problematic area. My primary use case is encouraging better discussions / review practices as opposed to getting PR reviews full of syntax stuff.

**Comment by djspiewak** [comment] 2018-09-10 21:38
> FWIW, I use scalafmt on compile on lots and lots of projects, both open & closed source, and I've never had problems with speed or generating bad code or loops

It really depends on the size of the project and the complexity of the files in question (complexity as defined by scalafmt, not in any normal sense). On quasar, for example, having scalafmt on compile adds about 5 seconds to every compile, even if just editing a single file which does not need to be reformatted! To make matters worse, a couple files in quasar also exhibit the looping behavior (I think I resolved this with noformat), and a couple other files exhibit extreme performance pathologies (requiring massive amounts of time to format the single file).

5 seconds between editor save and sudden reformat (if running `~compile` in the background) is completely insane and pretty much always results in lost work (as the editor has to resolve the conflict between the in-buffer changes you went on to make after save), even if 5 seconds tacked onto trivial compiles was considered acceptable overhead.

There's no question that scalafmt works a lot better on smaller projects with less, uh, *creative* use of Scala's syntax. I'm just raising the issue because cats is on the larger side (though not huge) and does have a couple syntactically thorny bits.

**Comment by ceedubs** [comment] 2018-09-10 22:04
See also #1206 and #1731

**Comment by abdheshkumar** [comment] 2018-09-23 23:06
We could run format code by scalafmt cli in git **pre-commit** hook to check compilation and formatting. Here are some references:
https://gist.github.com/cvogt/2676ed6c6d1abafa3d6a
https://medium.com/zyseme-technology/code-formatting-scalafmt-and-the-git-pre-commit-hook-3de71d099514

**Comment by easel** [comment] 2018-09-25 19:12
I'm a huge fan of scalafmt. Did we ever bikeshed out the appropriate settings? If not, let's do that and check them in. Then we can figure out out how to apply en-masse and enforce going forward.

**Comment by kailuowang** [comment] 2018-12-20 02:55
I am going to close this one for now since it's already in place.

**Closed by kailuowang** 2018-12-20 02:55 UTC
