### ISSUE TITLE
Make sure code generated by Boilerplate are tested

### ISSUE THREAD

**Issue by kailuowang** [typelevel/cats#1968] opened 2017-10-14 03:04 UTC
Right now a good portion of which is not. E.g. `SemigroupArityFunctions` and `ApplyArityFunctions`

**Comment by BennyHill** [comment] 2017-10-28 13:38
I believe this issue replicates #383, with the possible difference that #383 is specifically for auto generating the tests.

Perhaps best to clarify here and close #383 ?

**Comment by ceedubs** [comment] 2018-03-25 21:31
Closing as a duplicate of #383.

**Closed by ceedubs** 2018-03-25 21:31 UTC
