### ISSUE TITLE
Find a way to avert the CI failure `No output has been received in the last 10 minutes`

### ISSUE THREAD

**Issue by DavidGregory084** [typelevel/cats#810] opened 2016-01-16 15:18 UTC
CI builds occasionally fail due to the message:
```
No output has been received in the last 10 minutes, this potentially indicates a stalled build or something wrong with the build itself.
```
This is off-putting for newcomers as it's not immediately obvious that there might be nothing wrong with their PR.

Could we avert this by using the [travis_wait](https://docs.travis-ci.com/user/build-timeouts) command or is there some other way that we could speed up builds so they don't encounter this timeout?

**Comment by InTheNow** [comment] 2016-01-16 17:20
This is caused by a know bug that has been fixed in scalacheck, but not released. Might be best to wait on this for now.

**Comment by DavidGregory084** [comment] 2016-01-17 11:48
Ah, that makes sense. Shall we just close this, or wait for rickynils/scalacheck#195?

**Comment by paulp** [comment] 2016-03-18 19:47
Looking at  rickynils/scalacheck#195 I see this has been going on for six months. That's about 5.95 months too long when it comes to nondeterministic CI failures. They are huge time wasters.

**Comment by DavidGregory084** [comment] 2016-03-18 20:02
@paulp actually 1.13.0 is released now and it looks like cats is building against 1.12.5, maybe just needs a version bump?

**Comment by ceedubs** [comment] 2016-03-18 20:03
@DavidGregory084 I suspect we are going to run into https://github.com/rickynils/scalacheck/issues/218 if we do that.

**Comment by DavidGregory084** [comment] 2016-03-18 20:07
:cry:

**Comment by paulp** [comment] 2016-03-18 20:15
It doesn't even compile against 1.13.0. A little excerpt.
```
[error] /s/scala/cats/laws/src/main/scala/cats/laws/discipline/TraverseTests.scala:37: could not find implicit value for parameter a2: org.scalacheck.Arbitrary[A => M]
[error]         "traverse derive foldMap" -> forAll(laws.foldMapDerived[A, M] _)
[error]                                            ^
[error] /s/scala/cats/laws/src/main/scala/cats/laws/discipline/TraverseTests.scala:36: could not find implicit value for parameter a2: org.scalacheck.Arbitrary[A => X[B]]
[error]         "traverse parallel composition" -> forAll(laws.traverseParallelComposition[A, B, X, Y] _),
[error]                                                  ^
[error] 50 errors found
```

**Comment by ceedubs** [comment] 2016-03-19 13:05
@paulp I haven't really looked yet, so I could be totally wrong, but my guess is that those compile errors are in places where we've assumed that if we have an `Arbitrary[A]` we have an `Arbitrary[X => A]`. That was true with previous versions of Scalacheck, but only because it only produced arbitrary functions with a constant result value. I'm guessing we'll have to pass along those arbitrary function requirements (because we don't already have enough implicit parameters in there...).

**Comment by xuwei-k** [comment] 2016-03-19 13:15
You should define [`org.scalacheck.Cogen[X]`](https://github.com/rickynils/scalacheck/blob/1.13.0/src/main/scala/org/scalacheck/Cogen.scala) and `Arbitrary[A]` if you need `Arbitrary[X => A]`.

- https://github.com/rickynils/scalacheck/pull/171
- https://github.com/rickynils/scalacheck/blob/1.13.0/src/main/scala/org/scalacheck/ArbitraryArities.scala#L12

**Comment by ceedubs** [comment] 2016-03-19 13:23
Thanks, @xuwei-k.

**Comment by adelbertc** [comment] 2016-03-21 07:02
An attempt: https://github.com/typelevel/cats/pull/942

**Comment by ceedubs** [comment] 2016-05-14 12:36
I haven't seen this problem after some scala.js and scalacheck config changes that were introduced in recent months. I'm going to go ahead and close this out. Feel free to reopen it if it becomes a problem again.

**Closed by ceedubs** 2016-05-14 12:36 UTC
